config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => "users/registrations" } 
  devise_scope :user do
   get "users/autocomplete_entreprise_nom" => "users/registrations#autocomplete_entreprise_nom"
  end
  resources :markets

  resources :fournisseurs

  resources :consultations do
    get :autocomplete_fournisseur_nom, :on => :collection
  end

  resources :etablissements

  
   root 'consultations#index'

end

app/models/etablissement.rb
#     EPSILIM - EPSILIM - Gestion des fiches de non conformité
#     Copyright (C) 2014  Arnaud GARCIA - GCS EPSILIM
#                         
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Etablissement < ActiveRecord::Base
	before_save :pretty_name
	has_and_belongs_to_many :consultations
	has_many :users, as: :entreprise, dependent: :delete_all

	before_destroy {|etablissement| etablissement.consultations.clear}
	
	def pretty_name
		self.nom=nom.upcase
	end
end

app/controllers/etablissements_controller.rb
#     EPSILIM - EPSILIM - Gestion des fiches de non conformité
#     Copyright (C) 2014  Arnaud GARCIA - GCS EPSILIM
#                         
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

class EtablissementsController < ApplicationController
  load_and_authorize_resource
  before_action :set_etablissement, only: [:show, :edit, :update, :destroy]

  def index
    @etablissements = Etablissement.all
  end

  def show
  end

  def new
    @etablissement = Etablissement.new
  end

  def edit
  end

  def create
    @etablissement = Etablissement.new(etablissement_params)

    respond_to do |format|
      if @etablissement.save
        format.html { redirect_to @etablissement, notice: 'Etablissement was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @etablissement.update(etablissement_params)
        format.html { redirect_to @etablissement, notice: 'Etablissement was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @etablissement.destroy
    respond_to do |format|
      format.html { redirect_to etablissements_url, notice: 'Etablissement was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etablissement
      @etablissement = Etablissement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etablissement_params
      params.require(:etablissement).permit(:nom)
    end
end

app/views/etablissements/_form.html.erb
<%= bootstrap_form_for(@etablissement) do |f| %>

  <%= f.text_field :nom %>
  <%= f.submit %>
<% end %>

app/views/etablissements/edit.html.erb
<%= render "shared/bandeau", titre: "Edition", texte: "Mise à jour d'un établissement" %>
<div class="container">
  <%= render 'form' %>
  <%= destroy @etablissement %>
</div>

app/views/etablissements/index.html.erb
<%= render "shared/bandeau_new",
 titre: "Etablissements",
 texte: "Module d'administration de l'ensemble des établissements de la région.",
 path: new_etablissement_path%>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nom</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @etablissements.each do |etablissement| %>
        <tr>
          <td><%= link_to etablissement.nom, etablissement %></td>
          <td><%= edit edit_etablissement_path(etablissement) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/etablissements/new.html.erb
<%= render "shared/bandeau", titre: "Nouvel Etablissement", texte: "Création d'un nouvel établissement" %>
<div class="container">
  <%= render 'form' %>
</div>

app/views/etablissements/show.html.erb
<%= render "shared/bandeau", titre: "Etablissement", texte: "Liste des informations associées." %>
<div class="container">
  <p>
    <strong>Nom:</strong>
    <%= @etablissement.nom %>
  </p>
  <%= back etablissements_path %>
  <%= edit edit_etablissement_path(@etablissement) %>
</div>