config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => "users/registrations" } 
  devise_scope :user do
   get "users/autocomplete_entreprise_nom" => "users/registrations#autocomplete_entreprise_nom"
  end
  resources :markets

  resources :fournisseurs

  resources :consultations do
    get :autocomplete_fournisseur_nom, :on => :collection
  end

  resources :etablissements

  
   root 'consultations#index'

end

app/models/consultation.rb
#     EPSILIM - EPSILIM - Gestion des fiches de non conformité
#     Copyright (C) 2014  Arnaud GARCIA - GCS EPSILIM
#                         
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Consultation < ActiveRecord::Base
	has_and_belongs_to_many :etablissements	
	before_destroy {|consultation| consultation.etablissements.clear}
	has_many :markets, :dependent => :delete_all
	

	accepts_nested_attributes_for :markets, allow_destroy: true

	validates_presence_of :code
end

app/controllers/consultations_controller.rb
#     EPSILIM - EPSILIM - Gestion des fiches de non conformité
#     Copyright (C) 2014  Arnaud GARCIA - GCS EPSILIM
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

class ConsultationsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_consultation, only: [:show, :edit, :update, :destroy]
  autocomplete :fournisseur, :nom, :full => true

  def add_marche
    respond_to do |format|
      format.js
    end
  end

  def index
    @consultations = Consultation.all
  end

  def show
  end

  def new
    @consultation = Consultation.new
    @consultation.markets.first_or_initialize  
    @etablissements=Etablissement.all  
  end

  def edit
  end

  def create

    @consultation = Consultation.new(consultation_params)
    respond_to do |format|
      if @consultation.save
       format.html { redirect_to @consultation, notice: 'Consultation was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to @consultation, notice: 'Consultation was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def destroy
    @consultation.destroy
    respond_to do |format|
      format.html { redirect_to consultations_url, notice: 'Consultation was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_consultation
    @consultation = Consultation.find(params[:id])
    @etablissements=Etablissement.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def consultation_params   
    params.require(:consultation).permit(:code, :libelle, :debut, :fin,:etablissement_ids => [], :markets_attributes => [:id, :code, :fournisseur_id, :_destroy])
  end  
end

app/views/consultations/_form.html.erb
<%= bootstrap_nested_form_for(@consultation) do |f| %>
  <%= f.text_field :code %>
  <%= f.date_field :debut %>
  <%= f.date_field :fin %>
  <%= f.collection_check_boxes(:etablissement_ids, @etablissements, :id, :nom) %>

  <%= f.fields_for :markets %>
  <span class="glyphicon glyphicon-plus"></span>
  <%= f.link_to_add "Marché supplémentaire", :markets %>
  <br/>
  <br/>
  <%= f.submit %>
<% end %>

app/views/consultations/_market_fields.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Marché et fournisseur associé</h3>
  </div>
  <div class="panel-body">
<% market_fournisseur_id = SecureRandom.uuid %>
<%= f.text_field :code, label: "Code du marché" %>
<%= f.label 'Fournisseur' %><br/>
<%= f.autocomplete_field :fournisseur_nom, autocomplete_fournisseur_nom_consultations_path,id_element: "##{market_fournisseur_id}" %>
<i>Veuillez taper les premières lettres...</i>
<%= f.hidden_field :fournisseur_id, id: "#{market_fournisseur_id}" %>
<br/>
<%= f.link_to_remove "Supprimer le marché" %>
</div>
</div>

app/views/consultations/add_marche.js.erb
$('div#marches').append("<%= escape_javascript(render 'marche') %>");

app/views/consultations/edit.html.erb
<%= render "shared/bandeau", titre: "Edition", texte: "Mise à jour d'une consultation" %>
<div class="container">
  <%= render 'form' %>
  <%= destroy @consultation %>
</div>

app/views/consultations/index.html.erb
<%= render "shared/bandeau_new",
 titre: "Consultations",
 texte: "Module de gestion des consultations", path: new_consultation_path  %>

<div class="container">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Libelle</th>
      <th>Debut</th>
      <th>Fin</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @consultations.each do |consultation| %>
      <tr>
        <td><%= link_to consultation.code, consultation %></td>
        <td><%= consultation.libelle %></td>
        <td><%= consultation.debut %></td>
        <td><%= consultation.fin %></td>
        <td><%= edit edit_consultation_path(consultation) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/consultations/new.html.erb
<%= render "shared/bandeau", titre: "Consultation", texte: "Ajout d'une consultation" %>
<div class=container>
  <%= render 'form' %>
</div>

app/views/consultations/show.html.erb
<%= render "shared/bandeau", titre: "Consultation", texte: "Liste des informations associées." %>
<div class="container">
  <p>
    <strong>Code:</strong>
    <%= @consultation.code %>
  </p>
  <p>
    <strong>Libelle:</strong>
    <%= @consultation.libelle %>
  </p>
  <p>
    <strong>Debut:</strong>
    <%= @consultation.debut %>
  </p>
  <p>
    <strong>Fin:</strong>
    <%= @consultation.fin %>
  </p>
  <%= back consultations_path %>
  <%= edit edit_consultation_path(@consultation) %>
</div>