config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => "users/registrations" } 
  devise_scope :user do
   get "users/autocomplete_entreprise_nom" => "users/registrations#autocomplete_entreprise_nom"
  end
  resources :markets

  resources :fournisseurs

  resources :consultations do
    get :autocomplete_fournisseur_nom, :on => :collection
  end

  resources :etablissements

  
   root 'consultations#index'

end

app/models/fournisseur.rb
#     EPSILIM - EPSILIM - Gestion des fiches de non conformité
#     Copyright (C) 2014  Arnaud GARCIA - GCS EPSILIM
#                         
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Fournisseur < ActiveRecord::Base
	has_many :markets, :dependent => :delete_all
	has_many :users, as: :entreprise, dependent: :delete_all
end

app/controllers/fournisseurs_controller.rb
#     EPSILIM - EPSILIM - Gestion des fiches de non conformité
#     Copyright (C) 2014  Arnaud GARCIA - GCS EPSILIM
#                         
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

class FournisseursController < ApplicationController
  load_and_authorize_resource
  before_action :set_fournisseur, only: [:show, :edit, :update, :destroy]

  def index
    @fournisseurs = Fournisseur.all
  end

  def show
  end

  def new
    @fournisseur = Fournisseur.new
  end

  def edit
  end

  def create
    @fournisseur = Fournisseur.new(fournisseur_params)

    respond_to do |format|
      if @fournisseur.save
        format.html { redirect_to @fournisseur, notice: 'Fournisseur was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @fournisseur.update(fournisseur_params)
        format.html { redirect_to @fournisseur, notice: 'Fournisseur was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @fournisseur.destroy
    respond_to do |format|
      format.html { redirect_to fournisseurs_url, notice: 'Fournisseur was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fournisseur
      @fournisseur = Fournisseur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fournisseur_params
      params.require(:fournisseur).permit(:code, :nom, :email)
    end
end

app/views/fournisseurs/_form.html.erb
<%= bootstrap_form_for(@fournisseur) do |f| %>
  <%= error_notification(@fournisseur) %>
  <%= f.text_field :code %>
  <%= f.text_field :nom %>
  <%= f.email_field :email %>
  <%= f.submit %>
<% end %>

app/views/fournisseurs/edit.html.erb
<%= render "shared/bandeau", titre: "Edition", texte: "Mise à jour d'un fournisseur" %>
<div class="container">
  <%= render 'form' %>
  <%= destroy @fournisseur %>
</div>

app/views/fournisseurs/index.html.erb
<%= render "shared/bandeau_new",
 titre: "Fournisseurs",
 texte: "Module d'administration de l'ensemble des fournisseurs de la région. Les fournisseurs sont partagés par tous les établissements.",
 path: new_fournisseur_path%>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Raison sociale</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @fournisseurs.each do |fournisseur| %>
        <tr>
          <td><%= link_to fournisseur.id, fournisseur %></td>
          <td><%= fournisseur.nom %></td>
          <td><%= fournisseur.email %></td>
          <td><%= edit edit_fournisseur_path(fournisseur) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/fournisseurs/new.html.erb
<%= render "shared/bandeau", titre: "Nouveau Fournisseur", texte: "Création d'un nouveau fournisseur" %>
<div class="container">
  <%= render 'form' %>
</div>

app/views/fournisseurs/show.html.erb
<%= render "shared/bandeau", titre: "Fournisseur", texte: "Liste des informations associées." %>
<div class="container">
  <p>
    <strong>Code:</strong>
    <%= @fournisseur.code %>
  </p>
  <p>
    <strong>Raison sociale:</strong>
    <%= @fournisseur.nom %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @fournisseur.email %>
  </p>
  <%= back fournisseurs_path %>
  <%= edit edit_fournisseur_path(@fournisseur) %>
</div>